version: '3.7'
services:
  crawler:
    image: crawler
    container_name: crawler
    build:
      context: ./crawler
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 127.0.0.1:3000:3000
    # networks:
    #   - crawler
    network_mode: bridge
    external_links:
      - mysql-container
    environment:
      # - DB_URL=mysql-container
      - DB_PASSWD=@dm7815389mm
      - DB_PASSWD=admin
      - DB_USR=admin

  infoaqui:
    image: infoaqui
    container_name: infoaqui
    build:
      context: ./infoaqui
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    network_mode: bridge
    # networks: 
    #   - frontend
    #   - crawler
    links:
      - crawler
    environment:
      - CHOKIDAR_USEPOLLING=true

# networks:
#   # frontend:
#   # crawler:
#   default:
#     external: true
#     name: bridge 